### ISSUE TITLE
add code coverage

### ISSUE THREAD

**Issue by tpolecat** [typelevel/grackle#183]
Let's set up code coverage to help find areas we haven't tested.

**Comment by ahoy196** [comment]
Could you provide some guidance on what you would like to be the mechanism to set up the code coverage ? I'm a beginner and looking to make my first contribution to Grackle with this issue.

**Comment by milessabin** [comment]
Hmm ... I'm not sure we still want to go down this route (in which case, my apologies for not closing this issue). The complication is that the existing Scala coverage tools are somewhat flaky and sensitive to Scala version and platform, and in the past have caused more administrative effort than justified by the benefits they've provided.

@tpolecat do you have a view on this?

**Comment by armanbilge** [comment]
> and in the past have caused more administrative effort than justified by the benefits they've provided.

I think for now things seem okay. We've rolled out coverage to all the gemini-hlsw repos via sbt-lucuma. We also currently have coverage running in Skunk and http4s, specifically for JVM/2.13 which seems reliable enough.

FWIW, coverage is actually supported on JVM/JS/Native on Scala 2, and also Scala 3 but only JVM ...

**Comment by milessabin** [comment]
@armanbilge can you point us to a project to model on? If we want coverage results available on codecov.io do we need typelevel account credentials?

**Comment by armanbilge** [comment]
Here are two examples from Skunk and Cats Parse

https://github.com/typelevel/skunk/blob/1fad26f8838d689236f371909904d8e51f898c1d/build.sbt#L37-L47

https://github.com/typelevel/cats-parse/blob/79a414082fccb2e4db217712ae121d37494344a2/build.sbt#L32-L51

Pretty straightforward. No credentials necessary.

**Comment by ahoy196** [comment]
Thanks @armanbilge and @milessabin !

@milessabin I will take a look at this ... 👍

**Comment by ahoy196** [comment]
I posted a PR at #507 for review. Please take a look.

**Comment by milessabin** [comment]
Fixed in #507 and #508. Thanks!
