### ISSUE TITLE
Mapping validator for DB mappings should check that all fields for a type map to columns of the same table

### ISSUE THREAD

**Issue by rpiotrow** [typelevel/grackle#189]
Grackle doesn't support splitting the fields of a type between multiple tables (other than as subobjects). This is not checked by validator.

Full example with test can be found here: https://github.com/rpiotrow/gsp-graphql/commit/f443b3d7785d9c0df990bf57310766e388b9ba5d

**Comment by milessabin** [comment]
Nb. this is a stopgap until we have support for splitting types across multiple tables.
