### ISSUE TITLE
Change license to Apache 2

### ISSUE THREAD

**Issue by milessabin** [typelevel/grackle#196]
Possibly controversial. But I think that as part of the move to the Typelevel organisation this would make sense.

**Comment by lervag** [comment]
I think Apache 2 is a good choice for a license. But in the meantime, perhaps you could make the current license more visible in the Github repo? As far as I can understand, the current license is BSD-2.

**Comment by milessabin** [comment]
Mail proposing license change sent to all current contributors. I'll update when/if I get positive responses from everyone.

@lervag fair comment ... if I don't hear back in a few days I'll add the BSD license to the repo.

**Comment by milessabin** [comment]
All received responses approved the change. There's only one response outstanding (@yasuba :wave:), and I'll take the optimistic strategy.
