### ISSUE TITLE
Support GraphQL extensions

### ISSUE THREAD

**Issue by milessabin** [typelevel/grackle#21]
The GraphQL spec defines a simple extension mechanism for all types. This allows the definition of a new type by the addition of new elements of the appropriate sort to an existing type (eg. an addition field to an object type). This is currently not supported.

This can most likely be implemented as an elaboration/validation phase.

**Comment by milessabin** [comment]
Significant progress made in https://github.com/gemini-hlsw/gsp-graphql/pull/45.

**Comment by keirlawson** [comment]
I'd like to have a go at implementing this, any guidance/suggestions?

**Comment by keirlawson** [comment]
Should the `Schema` represent the final form of the types, ie including all fields that have been added via extension, or should it instead include bare type definitions alongside extension definitions, with the actual extension of the types happening later?

**Comment by milessabin** [comment]
I haven't given this a huge amount of thought, but I would probably model extensions fairly directly, ie. in the case of an object or an interface type extension I would represent them as an `XxxExtension` with a reference to the extended type and a list of the additional fields.

**Comment by milessabin** [comment]
I'd actually be very interested to know more about how you would like to use extensions, and what criteria you would use to choose between adding fields by adding directly to the base type vs. adding them via an extension.

**Comment by keirlawson** [comment]
> I'd actually be very interested to know more about how you would like to use extensions, and what criteria you would use to choose between adding fields by adding directly to the base type vs. adding them via an extension.

I'm intending to use Grackle's parser to do some validation on some pre-existing schemas that we currently use with Apollo, and some of these contain object extensions.  What the original rationale for their use is I'm not sure... I will ask.

**Comment by keirlawson** [comment]
Opened #258 as a first stepping stone
