### ISSUE TITLE
False positives in validator re: unmapped types

### ISSUE THREAD

**Issue by tpolecat** [typelevel/grackle#230]
Some mappings (like Generic or Json) can traverse structures reflectively and don't need explicit mappings for contained types. The validator doesn't know this (can it?) and reports errors for unmapped types.

**Comment by milessabin** [comment]
Yup, we're going to need to take a different approach to validation to make this work sensibly.

I think the right approach is to validate that all of a set of paths derivable from the schema are handled somehow. I think that's doable, at least to an reasonable approximation.

**Comment by milessabin** [comment]
Fixed in #608.
