### ISSUE TITLE
Schema @deprecated directive not supported for Input fields / arguments

### ISSUE THREAD

**Issue by dantb** [typelevel/grackle#382]
Small thing before I forget - `@deprecated` directives don't stick (though they're not rejected) when used on `Input` fields in a grackle `Schema`. This is in the [working draft](https://spec.graphql.org/draft/#sec--deprecated) of the GraphQL spec but not the [latest released version](https://spec.graphql.org/October2021/#sec--deprecated). Shall I add support or leave it for now? Also looks it will also be allowed on arguments in that version

**Comment by milessabin** [comment]
I think we'll probably want an overall ticket for supporting spec revisions.

**Comment by milessabin** [comment]
Fixed in #466.
