### ISSUE TITLE
Issue with SQL when migrating from an older grackle version

### ISSUE THREAD

**Issue by ryan-martin-itv** [typelevel/grackle#501]
I'm currently migrating some code from an older grackle version `0.0.49`.
I have some example code that reproduces the issue here: https://github.com/ryan-martin-itv/gql-test

Essentially I have a two tables that are joined together with two `Join` definitions in the type mapping.
In version `0.0.49` it produces this SQL:
```sql
SELECT inner.value, inner.id, inner.join, outer.id, outer.join, outer.value
FROM outer
LEFT JOIN inner ON outer.join = inner.join
WHERE (outer.value = ?) AND (outer.id = inner.id)
```

In any version after `0.8.0` it produces this SQL:
```sql
SELECT
  inner_outer_nested.id,
  inner_outer_nested.join,
  inner_outer_nested.value,
  outer.id    AS id_alias_0,
  outer.join  AS join_alias_1,
  outer.value AS value_alias_2
FROM outer
  INNER JOIN outer ON (outer.id = outer.id)
  INNER JOIN LATERAL (
    SELECT inner.join, inner.id, inner.value FROM inner
    INNER JOIN outer ON (outer.join = inner.join)
  ) AS inner_outer_nested
ON (inner_outer_nested.join = outer.join)
WHERE (outer.value = ?)
```

1. Is the SQL produced in the second example correct?
2. In the production code, it needs the extra `AND (outer.id = inner.id)` from the first query otherwise the query times out. Is there a way to add that back in?

**Comment by milessabin** [comment]
0.0.49 is an incredibly old version! Nearly two and a half years old!

Compilation to SQL has changed dramatically in that time, so I'm afraid it isn't helpful to compare old with new. If there's a performance issue with more recent versions, then we need to address that directly.

Does the 0.15.0 version in repo you linked to fully reproduce the problem?

**Comment by milessabin** [comment]
I suspect you probably need a composite join as illustrated [here](https://github.com/typelevel/grackle/blob/main/modules/sql/shared/src/test/scala/SqlCompositeKeyMapping.scala#L69). Could you try that with the 0.15.0 reproduction and let me know if that does the trick?

**Comment by milessabin** [comment]
Try this change,
```diff
-              SqlObject("inner", Join(outer.id, inner.id), Join(outer.join, inner.join))
+              SqlObject("inner", Join(List((outer.id, inner.id), (outer.join, inner.join))))
```
With that change the generated SQL looks like this,
```sql
SELECT
  inner.id,
  inner.join,
  inner.value,
  outer.id AS id_alias_0,
  outer.join AS join_alias_1,
  outer.value AS value_alias_2
FROM
  outer
  INNER JOIN inner ON (
    inner.id = outer.id
    AND inner.join = outer.join
  )
WHERE
  (outer.value = ?)
```
Which I think is what you're looking for.

**Comment by ryan-martin-itv** [comment]
Hi @milessabin 
The composite join worked :+1:
Thanks
