### ISSUE TITLE
Regression introduced in 0.18.1

### ISSUE THREAD

**Issue by umazalakain** [typelevel/grackle#590]
Version 0.18.1 introduced a bug not present in 0.18.0.
The following query was working correctly in 0.18.0:

```
{
  a {
    ... AFields
  }
}

fragment XFields on X {
  x
}

fragment YFields on Y {
  y
}

fragment AFields on A {
  ... XFields
  ... YFields
}
```

With a schema

```
type Query {
  a: A!
}

union A = X | Y

type X {
  x: String!
}

type Y {
  y: String!
}
```

In 0.18.1 we get an error `Fragment 'AFields' is not compatible with type 'A'`

I'll try to find some time and write a test case

**Comment by umazalakain** [comment]
Failing test case can be found in https://github.com/umazalakain/grackle/commit/6746b12671dd0c92a7ee0e30ed7d9d2267bf7d2d

**Comment by milessabin** [comment]
Fantastic ... thank you!
