### ISSUE TITLE
Fragment changes number of elements in a list

### ISSUE THREAD

**Issue by phdoerfler** [typelevel/grackle#606]
It is currently possible to reduce the number of returned elements by adding a fragment to the query.
For details, see the two new tests added by the PR:
https://github.com/phdoerfler/grackle/commit/2693a18fa906bf7e43eea02a5b682a75f8156dfa.
This happened because of a mistake where I had used the wrong column in my doobie table. This wrong column would always be null in the case where the fragment applied. If you change `RichText!` into `RichText` in the schema, the number of objects would correctly remain three albeit with `null` as description for the affected element.
Changing the view in the .sql file to use `c.description` instead of the wrong `i.description` avoids this bug.

**Comment by milessabin** [comment]
A perfect reproduction ... many thanks for that.

I'm really sure what I can do about this though. I think Grackle has to trust your view logic, and it has no independent way of determining how many elements there _ought_ to be in a result list.

I'm definitely open to ideas here, but for now I'm going to close this.

**Comment by som-snytt** [comment]
if you close as "not planned", then it's easier to distinguish purple ("some useful work was done") from gray ("nothing to see here").

**Comment by milessabin** [comment]
@som-snytt thanks for the tip!
