### ISSUE TITLE
Valid introspection query fails validation

### ISSUE THREAD

**Issue by ghostdogpr** [typelevel/grackle#622]
The following introspection query:
```graphql
query IntrospectionQuery {
  __schema {
    types {
      fields(includeDeprecated: true) {
        name
        type {
          ...TypeRef
        }
      }
    }
  }
}

fragment TypeRef on __Type {
  name
  ofType {
    name
    ...on __Type { kind }
  }
}
```
gives an error: `Unknown type '__Type' in type condition`.

It seems to happen since 0.17.1, it was working with 0.17.0.

**Comment by milessabin** [comment]
Thanks for the report!

That's very odd, because we have passing tests which are a superset of that query. I'll investigate.
